/**
 * Centralized enums for the application.
 * Using string enums for better readability and Prisma compatibility.
 */

export enum JobStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum RouteStatus {
  CV_PENDING = "CV_PENDING",
  CV_CREATED = "CV_CREATED",
  ANALYSIS_PENDING = "ANALYSIS_PENDING",
  ANALYSIS_DONE = "ANALYSIS_DONE",
  OPPORTUNITIES_PENDING = "OPPORTUNITIES_PENDING",
  OPPORTUNITIES_DONE = "OPPORTUNITIES_DONE",
  ROADMAP_PENDING = "ROADMAP_PENDING",
  ROADMAP_IN_PROGRESS = "ROADMAP_IN_PROGRESS",
  ROADMAP_DONE = "ROADMAP_DONE",
  PROGRAM_PENDING = "PROGRAM_PENDING",
  PROGRAM_IN_PROGRESS = "PROGRAM_IN_PROGRESS",
  PROGRAM_DONE = "PROGRAM_DONE",
}

export enum OpportunityType {
  INTERNSHIP = "INTERNSHIP",
  SCHOLARSHIP = "SCHOLARSHIP",
  EXCHANGE_PROGRAM = "EXCHANGE_PROGRAM",
  EMPLOYMENT = "EMPLOYMENT",
  STARTUP = "STARTUP",
}

export enum TaskType {
  ANALYSIS = "ANALYSIS",
  QUICK_MATCH = "QUICK_MATCH",
  CV_PROCESSING = "CV_PROCESSING",
  PROGRESS_TIMELINE = "PROGRESS_TIMELINE",
  ROADMAP_GENERATION = "ROADMAP_GENERATION",
}
